version: '3'
services:
  express-app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "mysql://user:userpass@db:3306/mydatabase"

  db:
    image: mysql/mysql-server:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "pass"
      MYSQL_DATABASE: "mydatabase"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "userpass"
